name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./chat/pom.xml
          mvn clean package -f ./train/pom.xml
          mvn clean package -f ./dashboard/pom.xml
          mvn clean package -f ./marketing/pom.xml

      - name: Docker Build and push for Chat
        uses: docker/build-push-action@v4
        with:
          context: ./chat
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/chat:latest
            ghcr.io/${{ github.repository }}/chat:${{ github.ref_name }}
            
      - name: Docker Build and push for Train
        uses: docker/build-push-action@v4
        with:
          context: ./train
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/train:latest
            ghcr.io/${{ github.repository }}/train:${{ github.ref_name }}
            
      - name: Docker Build and push for Dashboard
        uses: docker/build-push-action@v4
        with:
          context: ./dashboard
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/dashboard:latest
            ghcr.io/${{ github.repository }}/dashboard:${{ github.ref_name }}
            
      - name: Docker Build and push for Marketing
        uses: docker/build-push-action@v4
        with:
          context: ./marketing
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/marketing:latest
            ghcr.io/${{ github.repository }}/marketing:${{ github.ref_name }}
            
