server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: chat
          uri: http://localhost:8082
          predicates:
            - Path=/chats/**, 
        - id: train
          uri: http://localhost:8083
          predicates:
            - Path=/trains/**, 
        - id: dashboard
          uri: http://localhost:8084
          predicates:
            - Path=, 
        - id: marketing
          uri: http://localhost:8085
          predicates:
            - Path=/marketings/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: chat
          uri: http://chat:8080
          predicates:
            - Path=/chats/**, 
        - id: train
          uri: http://train:8080
          predicates:
            - Path=/trains/**, 
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path=, 
        - id: marketing
          uri: http://marketing:8080
          predicates:
            - Path=/marketings/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
